;;primer ejemplo lisp
;;(print "Hola Paco")
(
    defun separador()
    (print "------------")
)
( defun nombreAlumno (alumno)
    (print ( string-upcase (concatenate 'string "Nombre alumno:" alumno))
    )    
)
(
    defun notafinal2num (a b)
    (print (+ a b))
)
(
    defun aprobado (a)
    (print (if (> a 5) "APROBADO" "NO APROBADO"))
)
(
    defun califStr (a)
    (cond ((> a 9) "SOBRESALIENTE")
          ((OR (= a 8)(= a 7)) "NOTABLE")
          ((= a 6) "BIEN")
          ((= a 5) "APROBADO")
          (T "SUSPENDIDO")
    )
)
(
    defun notafinalTotal (lista)
    (print (reduce '+ lista))
)
(nombreAlumno "Paco")
(separador)
(notafinal2num 7.2 3)
(separador)
(aprobado 4)
(separador)
(print (califStr 4))
(separador)
(notafinalTotal '(7.2 3 5))